# Generated by Django 3.1.4 on 2021-06-07 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blogcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='heading',
        ),
    ]
